// 屁宝专属 IBD VP HK 岗位 mock 数据
// 真实公司、真实 sector、真实 office address，岗位为模拟
window.JOBS_DATA = [
  {
    id: "gs-001",
    company: "Goldman Sachs",
    companyShort: "GS",
    logoColor: "#7399C6",
    logoBg: "#0A2540",
    title: "Vice President, M&A — TMT",
    sector: "M&A",
    subSector: "TMT",
    location: "Cheung Kong Center, Central",
    postedDaysAgo: 0,
    postedDate: "2026-05-28",
    salary: "HK$2.4M–3.2M base + bonus",
    jdSummary: "Lead execution of cross-border M&A mandates across Greater China TMT clients. 6–9 yrs IBD experience required, fluent Mandarin + English. Prior bulge bracket or top boutique exposure.",
    keyReqs: ["6–9 yrs IBD", "Mandarin native", "Cross-border M&A", "TMT coverage"],
    applyUrl: "https://higher.gs.com/roles",
    isNew: true,
    isHot: true
  },
  {
    id: "ms-001",
    company: "Morgan Stanley",
    companyShort: "MS",
    logoColor: "#FFFFFF",
    logoBg: "#1B365D",
    title: "VP — Investment Banking, FIG",
    sector: "FIG",
    subSector: "Insurance & AM",
    location: "International Commerce Centre, Kowloon",
    postedDaysAgo: 0,
    postedDate: "2026-05-28",
    salary: "Competitive + carry potential",
    jdSummary: "Cover regional insurance and asset management clients. Lead deal teams on capital raising, M&A advisory, and strategic dialogues. CFA preferred.",
    keyReqs: ["FIG coverage", "5+ yrs", "CFA preferred", "Bilingual"],
    applyUrl: "https://morganstanley.com/careers",
    isNew: true,
    isHot: true
  },
  {
    id: "jpm-001",
    company: "J.P. Morgan",
    companyShort: "JPM",
    logoColor: "#FFFFFF",
    logoBg: "#7B2D26",
    title: "Vice President — Healthcare IB",
    sector: "Healthcare",
    subSector: "Biotech & Pharma",
    location: "Chater House, Central",
    postedDaysAgo: 1,
    postedDate: "2026-05-27",
    salary: "HK$2.2M–2.9M base",
    jdSummary: "Execute IPOs, follow-ons, and cross-border M&A for China healthcare clients. Strong technical (DCF / LBO / comps) and client-facing skills required.",
    keyReqs: ["Healthcare sector", "IPO experience", "Mandarin + English", "6+ yrs"],
    applyUrl: "https://careers.jpmorgan.com",
    isNew: true
  },
  {
    id: "citi-001",
    company: "Citi",
    companyShort: "Citi",
    logoColor: "#FFFFFF",
    logoBg: "#003B70",
    title: "VP — ECM, Asia ex-Japan",
    sector: "ECM",
    subSector: "Equity Capital Markets",
    location: "Champion Tower, Central",
    postedDaysAgo: 2,
    postedDate: "2026-05-26",
    salary: "HK$2.0M–2.6M + bonus",
    jdSummary: "Originate and execute IPOs, placements, and convertibles across Asia. Manage syndicate processes and lead client pitches.",
    keyReqs: ["ECM execution", "5+ yrs", "Syndicate experience"],
    applyUrl: "https://jobs.citi.com",
    isNew: true
  },
  {
    id: "bofa-001",
    company: "Bank of America",
    companyShort: "BofA",
    logoColor: "#E31837",
    logoBg: "#012169",
    title: "Vice President — Natural Resources IB",
    sector: "Natural Resources",
    subSector: "Energy & Mining",
    location: "Cheung Kong Center, Central",
    postedDaysAgo: 2,
    postedDate: "2026-05-26",
    salary: "HK$2.1M–2.8M base",
    jdSummary: "Coverage banker for Greater China energy, metals, and mining clients. Lead M&A and capital markets transactions.",
    keyReqs: ["Natural Resources", "M&A modeling", "Mandarin"],
    applyUrl: "https://careers.bankofamerica.com",
    isNew: false
  },
  {
    id: "ubs-001",
    company: "UBS",
    companyShort: "UBS",
    logoColor: "#E60000",
    logoBg: "#FFFFFF",
    title: "Executive Director / VP — M&A Asia",
    sector: "M&A",
    subSector: "Pan-Asia M&A",
    location: "Two IFC, Central",
    postedDaysAgo: 3,
    postedDate: "2026-05-25",
    salary: "HK$2.5M–3.4M + deferred",
    jdSummary: "Senior execution role on flagship Asia M&A mandates. Lead deal teams, manage client relationships, mentor associates and analysts.",
    keyReqs: ["7+ yrs IBD", "M&A execution", "Team leadership"],
    applyUrl: "https://www.ubs.com/careers",
    isNew: false,
    isHot: true
  },
  {
    id: "barc-001",
    company: "Barclays",
    companyShort: "BARC",
    logoColor: "#FFFFFF",
    logoBg: "#00AEEF",
    title: "VP — Industrials Investment Banking",
    sector: "Industrials",
    subSector: "Diversified Industrials",
    location: "Cheung Kong Center, Central",
    postedDaysAgo: 3,
    postedDate: "2026-05-25",
    salary: "Competitive",
    jdSummary: "Coverage and execution role for industrials clients across HK, China, and SE Asia. M&A, ECM, and DCM mandates.",
    keyReqs: ["Industrials", "5–8 yrs", "Cross-product"],
    applyUrl: "https://search.jobs.barclays",
    isNew: false
  },
  {
    id: "db-001",
    company: "Deutsche Bank",
    companyShort: "DB",
    logoColor: "#FFFFFF",
    logoBg: "#0018A8",
    title: "Vice President — DCM Origination",
    sector: "DCM",
    subSector: "Debt Capital Markets",
    location: "International Commerce Centre, Kowloon",
    postedDaysAgo: 4,
    postedDate: "2026-05-24",
    salary: "HK$1.9M–2.5M + bonus",
    jdSummary: "Originate USD and CNH bond mandates for Greater China corporates and FIs. Manage syndicate and investor dialogue.",
    keyReqs: ["DCM execution", "Asia HY/IG", "Mandarin"],
    applyUrl: "https://careers.db.com",
    isNew: false
  },
  {
    id: "hsbc-001",
    company: "HSBC",
    companyShort: "HSBC",
    logoColor: "#FFFFFF",
    logoBg: "#DB0011",
    title: "VP — Real Estate Group",
    sector: "Real Estate",
    subSector: "REITs & Developers",
    location: "HSBC Main Building, Central",
    postedDaysAgo: 4,
    postedDate: "2026-05-24",
    salary: "HK$1.8M–2.4M + bonus",
    jdSummary: "Coverage banker for HK and China real estate clients. Advise on REIT IPOs, M&A, and structured financings.",
    keyReqs: ["Real Estate", "REIT experience", "Cantonese a plus"],
    applyUrl: "https://www.hsbc.com/careers",
    isNew: false
  },
  {
    id: "sc-001",
    company: "Standard Chartered",
    companyShort: "SC",
    logoColor: "#0473EA",
    logoBg: "#FFFFFF",
    title: "VP — Capital Markets & Advisory, FIG",
    sector: "FIG",
    subSector: "Banks & NBFIs",
    location: "Standard Chartered Bank Building, Central",
    postedDaysAgo: 5,
    postedDate: "2026-05-23",
    salary: "HK$1.8M–2.3M",
    jdSummary: "Advise on capital structuring, AT1 issuance, and M&A for Asian banks and NBFIs. Strong credit and regulatory understanding required.",
    keyReqs: ["FIG", "AT1/Tier 2", "Basel III literate"],
    applyUrl: "https://scb.taleo.net",
    isNew: false
  },
  {
    id: "cicc-001",
    company: "CICC",
    companyShort: "CICC",
    logoColor: "#C8102E",
    logoBg: "#FFFFFF",
    title: "VP / Director — IBD HK, Industrials",
    sector: "Industrials",
    subSector: "New Energy & EV",
    location: "One IFC, Central",
    postedDaysAgo: 1,
    postedDate: "2026-05-27",
    salary: "HK$1.6M–2.2M + bonus",
    jdSummary: "Lead deal execution for HK-listed and pre-IPO industrials clients with focus on new energy. 母语普通话 essential.",
    keyReqs: ["Mandarin native", "HK IPO", "New Energy/EV"],
    applyUrl: "https://career.cicc.com",
    isNew: true
  },
  {
    id: "citics-001",
    company: "CITIC Securities",
    companyShort: "CITICS",
    logoColor: "#FFFFFF",
    logoBg: "#B81C25",
    title: "VP — Investment Banking, Tech",
    sector: "TMT",
    subSector: "Tech & Internet",
    location: "ICBC Tower, Central",
    postedDaysAgo: 2,
    postedDate: "2026-05-26",
    salary: "HK$1.5M–2.0M + 项目奖金",
    jdSummary: "覆盖中国科技互联网客户，主导 HK IPO、再融资及 H 股回归项目。5+ 年内资或外资投行经验。",
    keyReqs: ["TMT", "HK IPO", "Mandarin native", "5+ yrs"],
    applyUrl: "https://www.citics.com/careers",
    isNew: true
  },
  {
    id: "huatai-001",
    company: "Huatai International",
    companyShort: "HTSC",
    logoColor: "#FFFFFF",
    logoBg: "#C8102E",
    title: "VP — Healthcare Investment Banking",
    sector: "Healthcare",
    subSector: "Biotech & Medical Devices",
    location: "K11 ATELIER, Central",
    postedDaysAgo: 3,
    postedDate: "2026-05-25",
    salary: "HK$1.4M–1.9M",
    jdSummary: "执行香港 18A 生物科技 IPO 及跨境 M&A。需熟悉港交所上市规则。",
    keyReqs: ["18A IPO", "Healthcare", "Mandarin", "5+ yrs"],
    applyUrl: "https://www.htsc.com.hk/career",
    isNew: false
  },
  {
    id: "haitong-001",
    company: "Haitong International",
    companyShort: "HTI",
    logoColor: "#FFFFFF",
    logoBg: "#003D7C",
    title: "VP — ECM, Hong Kong",
    sector: "ECM",
    subSector: "IPO & Follow-on",
    location: "Li Po Chun Chambers, Central",
    postedDaysAgo: 5,
    postedDate: "2026-05-23",
    salary: "HK$1.4M–1.8M + bonus",
    jdSummary: "执行 HK IPO 项目，从 kickoff 到 listing 全流程管理。需熟悉港交所上市规则及 sponsor 工作。",
    keyReqs: ["HK ECM", "Sponsor work", "5+ yrs", "Mandarin"],
    applyUrl: "https://www.htisec.com/careers",
    isNew: false
  },
  {
    id: "nom-001",
    company: "Nomura",
    companyShort: "NOM",
    logoColor: "#FFFFFF",
    logoBg: "#C8102E",
    title: "VP — Cross-Border M&A Advisory",
    sector: "M&A",
    subSector: "Japan ↔ Greater China",
    location: "Three Exchange Square, Central",
    postedDaysAgo: 6,
    postedDate: "2026-05-22",
    salary: "HK$1.9M–2.5M",
    jdSummary: "Lead Japan-China cross-border M&A advisory mandates. Japanese language not required but a plus.",
    keyReqs: ["Cross-border M&A", "6+ yrs", "Japan exposure +"],
    applyUrl: "https://www.nomura.com/careers",
    isNew: false
  },
  {
    id: "miz-001",
    company: "Mizuho",
    companyShort: "MIZ",
    logoColor: "#FFFFFF",
    logoBg: "#1A4A8A",
    title: "VP — DCM, Asia",
    sector: "DCM",
    subSector: "Investment Grade",
    location: "K11 ATELIER, Tsim Sha Tsui",
    postedDaysAgo: 7,
    postedDate: "2026-05-21",
    salary: "Competitive",
    jdSummary: "Originate and execute Asian USD bond mandates with a focus on IG corporates and FIs.",
    keyReqs: ["DCM", "IG bonds", "5+ yrs"],
    applyUrl: "https://www.mizuhogroup.com/careers",
    isNew: false
  },
  {
    id: "mufg-001",
    company: "MUFG",
    companyShort: "MUFG",
    logoColor: "#FFFFFF",
    logoBg: "#C8102E",
    title: "Vice President — FIG Coverage",
    sector: "FIG",
    subSector: "Banks",
    location: "AIA Central, Central",
    postedDaysAgo: 8,
    postedDate: "2026-05-20",
    salary: "HK$1.7M–2.2M",
    jdSummary: "FIG coverage banker for Greater China and SE Asia financial institutions. Both M&A and DCM products in scope.",
    keyReqs: ["FIG", "Cross-product", "6+ yrs"],
    applyUrl: "https://www.mufgamericas.com/careers",
    isNew: false
  },
  {
    id: "jef-001",
    company: "Jefferies",
    companyShort: "JEF",
    logoColor: "#FFFFFF",
    logoBg: "#1F3864",
    title: "VP — M&A, Asia",
    sector: "M&A",
    subSector: "Mid-Market M&A",
    location: "Two IFC, Central",
    postedDaysAgo: 1,
    postedDate: "2026-05-27",
    salary: "HK$2.0M–2.7M + carry",
    jdSummary: "Execute mid-market M&A across consumer, tech, and industrials. Lean deal teams, high responsibility from day one.",
    keyReqs: ["M&A execution", "5–8 yrs", "Self-starter"],
    applyUrl: "https://www.jefferies.com/careers",
    isNew: true,
    isHot: true
  },
  {
    id: "laz-001",
    company: "Lazard",
    companyShort: "LAZ",
    logoColor: "#003366",
    logoBg: "#FFFFFF",
    title: "VP — Financial Advisory, Greater China",
    sector: "M&A",
    subSector: "Strategic Advisory",
    location: "One Pacific Place, Admiralty",
    postedDaysAgo: 4,
    postedDate: "2026-05-24",
    salary: "HK$2.2M–2.9M + meaningful bonus",
    jdSummary: "Pure-play M&A advisory in a small, senior-driven team. Direct exposure to MDs and clients from day one.",
    keyReqs: ["M&A", "Independent advisory", "6+ yrs"],
    applyUrl: "https://www.lazard.com/careers",
    isNew: false,
    isHot: true
  },
  {
    id: "roth-001",
    company: "Rothschild & Co",
    companyShort: "ROTH",
    logoColor: "#FFFFFF",
    logoBg: "#1B1B1B",
    title: "Vice President — Global Advisory",
    sector: "M&A",
    subSector: "Cross-border Advisory",
    location: "Two Exchange Square, Central",
    postedDaysAgo: 6,
    postedDate: "2026-05-22",
    salary: "HK$2.0M–2.6M",
    jdSummary: "Advise Asian corporates on cross-border M&A, restructuring, and strategic transactions. Boutique culture, deep mentorship.",
    keyReqs: ["M&A advisory", "5+ yrs", "Bilingual"],
    applyUrl: "https://rothschildandco.com/careers",
    isNew: false
  },
  {
    id: "moe-001",
    company: "Moelis & Company",
    companyShort: "MOE",
    logoColor: "#0F2D52",
    logoBg: "#FFFFFF",
    title: "VP — General M&A, Hong Kong",
    sector: "M&A",
    subSector: "Sponsors & Corporates",
    location: "Champion Tower, Central",
    postedDaysAgo: 2,
    postedDate: "2026-05-26",
    salary: "HK$2.3M–3.0M + meaningful equity",
    jdSummary: "Independent advisor model. Work directly with senior bankers on M&A and restructuring mandates across Asia.",
    keyReqs: ["M&A", "PE/sponsors", "5–9 yrs"],
    applyUrl: "https://careers.moelis.com",
    isNew: true,
    isHot: true
  },
  {
    id: "ever-001",
    company: "Evercore",
    companyShort: "EVR",
    logoColor: "#FFFFFF",
    logoBg: "#0B2545",
    title: "Vice President — Investment Banking",
    sector: "M&A",
    subSector: "Generalist Advisory",
    location: "Two IFC, Central",
    postedDaysAgo: 5,
    postedDate: "2026-05-23",
    salary: "HK$2.4M–3.2M",
    jdSummary: "Senior-driven advisory firm. VPs given significant client and execution responsibility on complex strategic mandates.",
    keyReqs: ["M&A advisory", "6+ yrs", "Top-tier credentials"],
    applyUrl: "https://www.evercore.com/careers",
    isNew: false,
    isHot: true
  }
];

// 计算 today's stats
window.JOB_STATS = (() => {
  const jobs = window.JOBS_DATA;
  const newToday = jobs.filter(j => j.postedDaysAgo === 0).length;
  const newThisWeek = jobs.filter(j => j.postedDaysAgo <= 7).length;
  const hot = jobs.filter(j => j.isHot).length;
  return { newToday, newThisWeek, hot, total: jobs.length };
})();

// 申请进度 pipeline — 全站统一引用
window.PIPELINE = [
  { key: "interested", step: "01", label: "感兴趣",  en: "Watching",    tone: "gold"  },
  { key: "applied",    step: "02", label: "已投递",  en: "Applied",     tone: "blue"  },
  { key: "first",      step: "03", label: "初面",    en: "1st Round",   tone: "green" },
  { key: "final",      step: "04", label: "终面",    en: "Final Round", tone: "green" },
  { key: "offer",      step: "05", label: "Offer",   en: "Offer",       tone: "offer" }
];
window.PIPELINE_KEYS = window.PIPELINE.map(s => s.key);
window.STAGE_MAP = Object.fromEntries(window.PIPELINE.map(s => [s.key, s]));

// 加油语 pool — 屁宝早上打开时随机一条
window.GREETINGS = [
  { line: "屁宝，今天也要相信自己。", sub: "VP 的位置是为有准备的人留的。" },
  { line: "你比你以为的更厉害。", sub: "每一份 deck、每一次 pitch，都让你离 MD 更近一步。" },
  { line: "Good morning, 屁宝 ☀️", sub: "今天看哪家公司顺眼，就投哪家。" },
  { line: "稳一点，他们会发现你的。", sub: "你的 track record 已经在替你说话了。" },
  { line: "今天是个适合发简历的日子。", sub: "HKEX 开盘前，先开屁宝的 Bloomberg。" },
  { line: "屁宝牌投行雷达 已就绪。", sub: "Agent 跑了一整夜，给你筛出新机会。" },
  { line: "把面试当作 reverse interview。", sub: "你也在挑他们 —— 别忘了这一点。" },
  { line: "你已经走得很远了。", sub: "再投几份，就到下一个 chapter。" }
];
